name: ImagePublisher
on:
  push:
    branches:
      - master
      - main
  # TODO: just for test
  pull_request:
jobs:
  publish-image:
    name: publish images
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.x
      - name: build images
        env:
          REGISTRY: ${{secrets.SWR_REGISTRY}}
          REGISTRY_USER_NAME: ${{secrets.SWR_REGISTRY_USER_NAME}}
          REGISTRY_PASSWORD: ${{secrets.SWR_REGISTRY_PASSWORD}}
          REGISTRY_SERVER_ADDRESS: ${{secrets.SWR_REGISTRY_SERVER_ADDRESS}}
          INVALID_ENV: ${{secrets.NOT_EXIST}}
          NEW_ENV: "MY TESTING"
          VERSION: latest

        run: echo "$NEW_ENV"
